apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: rohanpatidar18/flaskapp:12  # Ensure this image exists in Minikube's Docker environment
        ports:
        - containerPort: 3000
