apiVersion: v1
kind: Service
metadata:
  name: reactapp-service
spec:
  selector:
    app: reactapp
  ports:
    - protocol: TCP
      port: 5000  # React app typically serves on port 80
      targetPort: 5000  # Matches the React container's port
  type: LoadBalancer  # Changed from LoadBalancer to NodePort for Minikube compatibility
